### PR TITLE
fix for getColumns() call on tables with textarea & teextinput fields

### PR DESCRIPTION
**Pull request by npinansky**
This fixes issue #13

### CODE REVIEW

**Comment by WellingGuzman** [comment]
I see the problem you are referring to, while we thank you for the effort and the nice bug you reported, this is not the proper solution, this is an issue with the API 1.0 response, we have been trying to solve it, but can't change much for legacy support, but we do fix it on 1.1.

The solution here is to add a proper solution to force for a `EntryCollection` in some way.

Thanks to you we also found some related to bug to getting the columns using local connection.

We are going to keep an eye on this issue, but unfortunately this PR wouldn't work because is not related to any interface, unless I'm wrong, but please show us more information about this.

**Comment by npinansky** [comment]
Hi,

I am sorry  I am having some trouble understanding your reply, can you please confirm if  i am getting this right, it seems to me you are saying if i switch to the 1.1 API , the problem will go away without any code patches?

**Comment by WellingGuzman** [comment]
Exactly, if you use `1.1`, you should be able to get the right information of all columns.

For 1.0 I will have to do some fixed instructions for `getColumns()`

**Comment by npinansky** [comment]
So I gave that a shot (i've omitted the hostname of our app server for security reasons) and I uncovered a bit of a problem with the 1.1 API, in the case of passing an invalid table name it fails without a clear error (see below) so my question is, 1.1 actually production ready? is it safe to be using it?

curl http://OUR_APP_SERVER/api/1.1/tables/plans/columns?access_token=dB6xx2LTIpA7oyMU

{
  "code":2,
  "class":"ErrorException",
  "message":"array_merge(): Argument #1 is not an array",
  "file":"\/var\/www\/directus\/vendor\/directus\/database\/SchemaManager.php",
  "line":120,
  "trace":[
    {
      "function":"handleErrors",
      "class":"Slim\\Slim",
      "type":"::",
      "args":[
        2,
        "array_merge(): Argument #1 is not an array",
        "\/var\/www\/directus\/vendor\/directus\/database\/SchemaManager.php",
        120,
        {
          "tableName":"plans",
          "params":[
            
          ],
          "skipCache":false,
          "tableSchema":null,
          "tableResult":{
            
          },
          "tableData":false
        }
      ]
    },
    {
      "file":"\/var\/www\/directus\/vendor\/directus\/database\/SchemaManager.php",
      "line":120,
      "function":"array_merge",
      "args":[
        false,
        {
          "schema":"directus"
        }
      ]
    },
    {
      "file":"\/var\/www\/directus\/vendor\/directus\/database\/TableSchema.php",
      "line":161,
      "function":"getTableSchema",
      "class":"Directus\\Database\\SchemaManager",
      "type":"->",
      "args":[
        "plans",
        [
          
        ],
        false
      ]
    },
    {
      "file":"\/var\/www\/directus\/vendor\/directus\/database\/TableSchema.php",
      "line":175,
      "function":"getTableSchema",
      "class":"Directus\\Database\\TableSchema",
      "type":"::",
      "args":[
        "plans",
        [
          
        ],
        false
      ]
    },
    {
      "file":"\/var\/www\/directus\/api\/routes\/A1\/Table.php",
      "line":106,
      "function":"getTableColumnsSchema",
      "class":"Directus\\Database\\TableSchema",
      "type":"::",
      "args":[
        "plans"
      ]
    },
    {
      "function":"columns",
      "class":"Directus\\API\\Routes\\A1\\Table",
      "type":"->",
      "args":[
        "plans"
      ]
    },
    {
      "file":"\/var\/www\/directus\/vendor\/slim\/slim\/Slim\/Route.php",
      "line":436,
      "function":"call_user_func_array",
      "args":[
        [
          {
            
          },
          "columns"
        ],
        [
          "plans"
        ]
      ]
    },
    {
      "file":"\/var\/www\/directus\/vendor\/slim\/slim\/Slim\/Slim.php",
      "line":1305,
      "function":"dispatch",
      "class":"Slim\\Route",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/var\/www\/directus\/vendor\/slim\/slim\/Slim\/Middleware\/Flash.php",
      "line":85,
      "function":"call",
      "class":"Slim\\Slim",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/var\/www\/directus\/vendor\/slim\/slim\/Slim\/Middleware\/MethodOverride.php",
      "line":92,
      "function":"call",
      "class":"Slim\\Middleware\\Flash",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/var\/www\/directus\/api\/core\/Directus\/Slim\/CorsMiddleware.php",
      "line":22,
      "function":"call",
      "class":"Slim\\Middleware\\MethodOverride",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/var\/www\/directus\/vendor\/slim\/slim\/Slim\/Slim.php",
      "line":1254,
      "function":"call",
      "class":"Directus\\Slim\\CorsMiddleware",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/var\/www\/directus\/api\/core\/Directus\/Application\/Application.php",
      "line":80,
      "function":"run",
      "class":"Slim\\Slim",
      "type":"->",
      "args":[
        
      ]
    },
    {
      "file":"\/var\/www\/directus\/api\/api.php",
      "line":1933,
      "function":"run",
      "class":"Directus\\Application\\Application",
      "type":"->",
      "args":[
        
      ]
    }
  ],
  "traceAsString":"#0 [internal function]: Slim\\Slim::handleErrors(2, 'array_merge(): ...', '\/var\/www\/direct...', 120, Array)\n#1 \/var\/www\/directus\/vendor\/directus\/database\/SchemaManager.php(120): array_merge(false, Array)\n#2 \/var\/www\/directus\/vendor\/directus\/database\/TableSchema.php(161): Directus\\Database\\SchemaManager->getTableSchema('plans', Array, false)\n#3 \/var\/www\/directus\/vendor\/directus\/database\/TableSchema.php(175): Directus\\Database\\TableSchema::getTableSchema('plans', Array, false)\n#4 \/var\/www\/directus\/api\/routes\/A1\/Table.php(106): Directus\\Database\\TableSchema::getTableColumnsSchema('plans')\n#5 [internal function]: Directus\\API\\Routes\\A1\\Table->columns('plans')\n#6 \/var\/www\/directus\/vendor\/slim\/slim\/Slim\/Route.php(436): call_user_func_array(Array, Array)\n#7 \/var\/www\/directus\/vendor\/slim\/slim\/Slim\/Slim.php(1305): Slim\\Route->dispatch()\n#8 \/var\/www\/directus\/vendor\/slim\/slim\/Slim\/Middleware\/Flash.php(85): Slim\\Slim->call()\n#9 \/var\/www\/directus\/vendor\/slim\/slim\/Slim\/Middleware\/MethodOverride.php(92): Slim\\Middleware\\Flash->call()\n#10 \/var\/www\/directus\/api\/core\/Directus\/Slim\/CorsMiddleware.php(22): Slim\\Middleware\\MethodOverride->call()\n#11 \/var\/www\/directus\/vendor\/slim\/slim\/Slim\/Slim.php(1254): Directus\\Slim\\CorsMiddleware->call()\n#12 \/var\/www\/directus\/api\/core\/Directus\/Application\/Application.php(80): Slim\\Slim->run()\n#13 \/var\/www\/directus\/api\/api.php(1933): Directus\\Application\\Application->run()\n#14 {main}"
}

**Comment by npinansky** [comment]
However the request did work as advertise when using the proper table name, so thank you!

**Comment by WellingGuzman** [comment]
Yes, the API 1.1, is production ready, some bugs like this one has been fixed already, maybe you are using an old version or we didn't push the release tag.

What SDK version are you using? and what `directus-database` package version was installed (with commit hash will be perfect)

**Pull request closed without merging**
